const main = document.querySelector('main');
const projects = window.reviewData.projects;
const categories = ['전체','그래픽','웹 디자인','UI·UX','프론트엔드'];
const reviewParams = new URLSearchParams(location.search);
if(reviewParams.get('name')==='long') window.reviewData.name='[긴 공개 이름 검토용]';
if(reviewParams.get('name')==='english') window.reviewData.name='[Independent Design Studio]';
if(reviewParams.get('title')==='english') projects[0].title='Designing a clear and accessible digital experience for complex information across responsive interfaces';
document.querySelector('.brand').firstChild.textContent=window.reviewData.name;
document.querySelector('.footer>a').textContent=window.reviewData.name;
document.querySelector('.menu-top').firstChild.textContent=window.reviewData.name;
let activeFilter = '전체';
const card = p => `<article class="project-card"><a href="#detail/${p.id}"><div class="image-frame"><img src="${p.image}" alt="${p.ratio} 구성 검토용 도형 이미지" width="960" height="720"></div><div class="card-meta"><span>${p.categories.join(' · ')}</span><span>검토용</span></div><h3>${p.title}</h3></a>${p.summary ? `<p>${p.summary}</p>` : ''}</article>`;
const services = () => `<section id="home-services" class="dark section"><div class="wrap services"><div><p class="eyebrow en">WHAT I DO</p><h2>디자인에서<br>화면 구현까지.</h2></div><div class="services-list"><div><h3>그래픽 디자인</h3><p>정보와 메시지를 전달하는 시각 표현을 구성합니다.</p></div><div><h3>웹 · UI/UX 디자인</h3><p>콘텐츠 구조와 사용 흐름을 정리하고 화면을 설계합니다.</p></div><div><h3>프론트엔드</h3><p>디자인을 반응형 웹 화면으로 구현합니다.</p></div><a class="text-link" href="#contact">필요한 작업 이야기하기 <span>↗</span></a></div></div></section>`;
function home(){return `<section class="hero wrap"><p class="eyebrow en">INDEPENDENT DESIGN & DEVELOPMENT</p><h1>${window.reviewData.name}</h1><div class="hero-bottom"><div class="hero-fields">그래픽 · 웹 · UI/UX<br>프론트엔드</div><div class="hero-description"><p>그래픽·웹·UI/UX 디자인과<br>프론트엔드 작업을 합니다.<br>필요한 디자인과 화면 구현 범위를<br>함께 정리합니다.</p><a class="text-link" href="#projects">프로젝트 보기 <span>↗</span></a></div></div><div class="hero-caption"><span>생각을 정리하고, 화면으로 만듭니다.</span><span class="en">SCROLL TO EXPLORE ↓</span></div></section><section class="section wrap"><div class="section-heading"><h2>선별한 작업</h2><a href="#projects">전체 프로젝트 ↗</a></div><div class="project-grid">${projects.slice(0,2).map(card).join('')}</div></section>${services()}`}
function listing(){const items=projects.filter(p=>activeFilter==='전체'||p.categories.includes(activeFilter));return `<section class="wrap page-heading"><p class="eyebrow en">PROJECTS</p><h1>작업의 기록.</h1><div class="heading-bottom"><p>그래픽부터 웹 화면 구현까지.<br>분야별로 작업을 살펴보세요.</p><span class="small muted">모든 항목은 디자인 검토용입니다.</span></div></section><section class="wrap listing"><div class="filters" role="group" aria-label="프로젝트 분야">${categories.map(c=>`<button data-filter="${c}" aria-pressed="${activeFilter===c}">${c}</button>`).join('')}</div><div class="project-grid">${items.map(card).join('')}</div>${items.length?'':'<p class="empty">이 분야에 표시할 작업이 없습니다.</p>'}</section>`}
function detail(id){const p=projects.find(p=>p.id===id)||projects[0];return `<section class="wrap page-heading"><a class="small" href="#projects">← 프로젝트 목록</a><p class="eyebrow en" style="margin-top:2.5rem">PROJECT STUDY / ${p.id.toUpperCase()}</p><h1 class="detail-heading">${p.title}</h1><p class="muted">실제 프로젝트가 아닌 블록 구성과 콘텐츠 변화 검토용 상세입니다.</p><dl class="detail-info"><div><dt>분야</dt><dd>${p.categories.join(' · ')}</dd></div><div><dt>수행 역할</dt><dd>실제 자료 등록 후 입력</dd></div><div><dt>기간</dt><dd>실제 자료 등록 후 입력</dd></div></dl></section><div class="wrap"><div class="detail-hero"><img src="${p.image}" alt="대표 이미지 배치 검토용 도형"></div><section class="block text-block"><h2>프로젝트의 맥락</h2><p>이 영역에는 작업의 배경, 해결해야 했던 문제, 본인이 맡은 범위를 작성합니다. 설명이 길어져도 편안하게 읽을 수 있도록 본문 너비를 제한합니다. 실제 경력이나 성과는 자료를 확인한 뒤 입력합니다.</p></section><section class="block two-images"><figure><img src="assets/graphic.svg" alt="세로형 이미지 비율 검토"><figcaption>세로 이미지 · 원본 비율 유지</figcaption></figure><figure><img src="assets/interface.svg" alt="정사각 이미지 비율 검토"><figcaption>정사각 이미지 · 모바일에서 아래로 배치</figcaption></figure></section><section class="block"><p class="small muted" style="margin-bottom:1rem">HTML·CSS 자유 블록 · 격리 배치 시안</p><iframe class="free-block" title="검토용 자유 블록" sandbox src="free-block.html"></iframe></section><section class="block text-block"><h2>진행 과정과 결과</h2><p>공통 블록은 같은 서체와 여백 규칙을 따릅니다. 자유 블록 뒤에서도 이 영역의 스타일은 유지됩니다. 수치나 평가 대신 실제 확인할 수 있는 결과물과 담당 범위를 설명합니다.</p></section><div class="block next-work"><a href="#projects">← 목록으로 돌아가기</a><a href="#contact">비슷한 작업 문의하기 ↗</a></div></div>`}
function contact(){return `<section class="dark contact"><div class="wrap contact-layout"><div class="contact-intro"><p class="eyebrow en">LET’S TALK</p><h1>어떤 작업을<br>생각하고<br>계신가요?</h1><p>기획·일정·예산이 모두 정해지지 않아도 괜찮습니다. 현재 생각하고 계신 내용을 알려주세요.</p><div class="contact-note"><p class="en">English inquiries are welcome.</p><p class="muted">연락 이메일은 공개 전 등록 예정입니다.</p><p class="muted" style="margin-top:1rem">이 화면은 입력과 결과 안내를 검토하는 시안입니다. 내용을 저장하거나 전송하지 않습니다.</p></div></div><form class="contact-form"><div class="form-grid"><div class="field"><label for="name">이름 / 담당자 <span>필수</span></label><input id="name" name="name" autocomplete="name" required placeholder="어떻게 불러드리면 될까요?"></div><div class="field"><label for="email">회신 이메일 <span>필수</span></label><input id="email" name="email" type="email" autocomplete="email" required placeholder="답변받으실 이메일"></div></div><div class="field"><label for="company">회사 / 팀 <span>선택</span></label><input id="company" autocomplete="organization" placeholder="개인 의뢰도 가능합니다"></div><div class="form-grid"><div class="field"><label for="schedule">희망 일정 <span>선택</span></label><select id="schedule"><option>아직 미정</option><option>상담 후 결정</option><option>1개월 이내 시작 희망</option><option>3개월 이내 시작 희망</option></select></div><div class="field"><label for="budget">예산 <span>선택</span></label><select id="budget"><option>상담 후 결정</option><option>예산 범위 있음 · 내용에 작성</option></select></div></div><div class="field"><label for="message">문의 내용 <span>필수</span></label><textarea id="message" required placeholder="필요한 작업, 현재 준비 상황, 참고 링크 등을 편하게 알려주세요."></textarea></div><label class="check"><input type="checkbox" required><span>개인정보 안내·동의 항목의 배치 검토용입니다.<br>이 시안에서는 개인정보를 수집하지 않습니다.</span></label><button type="submit" class="submit">결과 안내 시연 <span>↗</span></button><div class="demo-controls"><label for="scenario">검토할 처리 상황</label><select id="scenario"><option value="success">저장 성공</option><option value="failure">저장 실패</option><option value="notification">저장 성공 · 알림 실패</option></select></div><p class="form-result" role="status" aria-live="polite"></p></form></div></section>`}
function render(){const route=location.hash.slice(1)||'home';if(route==='main'){main.focus();return;}main.innerHTML=route==='projects'?listing():route==='contact'?contact():route.startsWith('detail/')?detail(route.split('/')[1]):home();if(reviewParams.get('name')==='english' && !['projects','contact'].includes(route) && !route.startsWith('detail/'))main.querySelector('h1')?.classList.add('en');document.querySelectorAll('.header nav a').forEach(a=>{if(a.hash===location.hash)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});if(route==='home-services'){document.getElementById(route).scrollIntoView()}else{window.scrollTo(0,0)}document.title=({projects:'프로젝트',contact:'문의'}[route]|| (route.startsWith('detail/')?'프로젝트 상세':'홈'))+' · 대표 시안';}
main.addEventListener('click',e=>{const button=e.target.closest('[data-filter]');if(button){const y=window.scrollY;activeFilter=button.dataset.filter;main.innerHTML=listing();window.scrollTo(0,y);main.querySelector(`[data-filter="${activeFilter}"]`).focus({preventScroll:true})}});
main.addEventListener('submit',e=>{e.preventDefault();const scenario=document.getElementById('scenario').value;const message={success:'[시연] 문의가 접수되었습니다. 실제 저장·전송은 하지 않았습니다.',failure:'[시연] 문의를 저장하지 못했습니다. 입력 내용은 유지됩니다. 다시 시도하거나 이메일로 연락해 주세요.',notification:'[시연] 문의는 접수되었으나 담당자 알림이 지연되고 있습니다. 운영 시에는 알림을 재시도합니다. 실제 저장·전송은 하지 않았습니다.'};document.querySelector('.form-result').textContent=message[scenario]});
const menu=document.querySelector('dialog');const toggle=document.querySelector('.menu-toggle');toggle.addEventListener('click',()=>{menu.showModal();toggle.setAttribute('aria-expanded','true')});function closeMenu(){menu.close();toggle.setAttribute('aria-expanded','false')}menu.querySelector('.menu-close').addEventListener('click',closeMenu);menu.addEventListener('click',e=>{if(e.target.closest('a'))closeMenu()});menu.addEventListener('close',()=>toggle.setAttribute('aria-expanded','false'));window.addEventListener('hashchange',render);render();
