import {labels,assets,initialProject,createBlock,duplicateBlock,moveBlock,validateProject} from './block-model.mjs';
const key='portfolio-block-study-v1';const status=document.getElementById('save-status');let project=initialProject();let loadError=false;
try{const saved=localStorage.getItem(key);if(saved)project=validateProject(JSON.parse(saved));}catch{loadError=true;}
let selected=project.blocks[0]?.id;let dirty=false;const history=[];let dragId=null;const preview=document.getElementById('editor-preview');
const make=(tag,text)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;return el;};
function snapshot(){history.push(structuredClone(project));if(history.length>30)history.shift();document.getElementById('undo').disabled=false;}
function changed(){dirty=true;status.textContent='저장하지 않은 변경이 있습니다.';sendPreview();}
function sendPreview(){preview.contentWindow?.postMessage({type:'portfolio-preview',project},location.origin);}
window.addEventListener('message',event=>{if(event.origin===location.origin&&event.source===preview.contentWindow&&event.data?.type==='portfolio-preview-ready')sendPreview();});
function renderList(){const list=document.getElementById('block-list');list.replaceChildren();document.getElementById('block-count').textContent=`${project.blocks.length}개`;project.blocks.forEach((b,i)=>{const row=make('li');row.className='block-row';row.dataset.id=b.id;row.setAttribute('aria-current',String(b.id===selected));row.draggable=true;const select=make('button');select.className='select-block';select.append(make('span',`${i+1}. ${labels[b.type]}`),make('small',b.heading||b.caption||b.label||'블록 선택'));select.addEventListener('click',()=>{selected=b.id;renderList();renderFields();});const order=make('div');order.className='order-actions';for(const [direction,label] of [[-1,'위로'],[1,'아래로']]){const button=make('button',label);button.setAttribute('aria-label',`${i+1}번 블록 ${label}`);button.disabled=i+direction<0||i+direction>=project.blocks.length;button.addEventListener('click',()=>{snapshot();project.blocks=moveBlock(project.blocks,b.id,i+direction);changed();renderList();});order.append(button);}row.append(select,order);row.addEventListener('dragstart',e=>{dragId=b.id;e.dataTransfer.setData('text/plain',b.id);});row.addEventListener('dragover',e=>{e.preventDefault();row.classList.add('drag-over');});row.addEventListener('dragleave',()=>row.classList.remove('drag-over'));row.addEventListener('drop',e=>{e.preventDefault();row.classList.remove('drag-over');if(dragId&&dragId!==b.id){snapshot();project.blocks=moveBlock(project.blocks,dragId,i);changed();renderList();}dragId=null;});row.addEventListener('dragend',()=>{dragId=null;document.querySelectorAll('.drag-over').forEach(r=>r.classList.remove('drag-over'));});list.append(row);});}
function field(root,b,name,label,options){const id=`field-${name}`;const labelEl=make('label',label);labelEl.htmlFor=id;let input;if(options){input=make('select');for(const [value,text]of options){const option=make('option',text);option.value=value;input.append(option);}}else{input=make(['body','caption'].includes(name)?'textarea':'input');if(input.tagName==='TEXTAREA')input.rows=name==='body'?6:2;}input.id=id;input.value=b[name];input.addEventListener(options?'change':'input',()=>{snapshot();b[name]=input.value;changed();const small=document.querySelector(`.block-row[data-id="${b.id}"] small`);if(small)small.textContent=b.heading||b.caption||b.label||'블록 선택';});root.append(labelEl,input);}
function renderFields(){const root=document.getElementById('block-fields');root.replaceChildren();const b=project.blocks.find(b=>b.id===selected);document.getElementById('duplicate').disabled=!b;document.getElementById('delete').disabled=!b;if(!b){root.append(make('p','블록을 추가하거나 선택하세요.'));return;}const assetOptions=assets.map(a=>[a.src,a.label]);if(b.type==='text'){field(root,b,'heading','섹션 제목');field(root,b,'body','본문');}if(b.type==='image'||b.type==='pair'){field(root,b,'src','이미지',assetOptions);field(root,b,'alt','이미지 대체 텍스트');if(b.type==='pair'){field(root,b,'secondSrc','두 번째 이미지',assetOptions);field(root,b,'secondAlt','두 번째 대체 텍스트');}else field(root,b,'fit','이미지 표시',[['contain','원본 비율 유지'],['cover','4:3 프레임 채우기']]);field(root,b,'caption','이미지 설명');}if(b.type==='info'){field(root,b,'body','정보 목록 · 한 줄에 항목: 내용');}if(b.type==='link'){field(root,b,'label','링크 문구');field(root,b,'url','링크 주소');}if(b.type==='space'){const checkbox=make('input');checkbox.type='checkbox';checkbox.id='line-toggle';checkbox.checked=b.line;checkbox.style.width='auto';const label=make('label','구분선 표시');label.htmlFor=checkbox.id;checkbox.addEventListener('change',()=>{snapshot();b.line=checkbox.checked;changed();});root.append(label,checkbox);}field(root,b,'width','본문 폭',[['wide','넓은 폭'],['reading','읽기 폭 · 740px']]);field(root,b,'spacing','블록 앞뒤 간격',[['small','작게'],['normal','기본'],['large','넓게']]);}
function refresh(){document.getElementById('project-title').value=project.title;document.getElementById('project-summary').value=project.summary;renderList();renderFields();sendPreview();}
for(const [id,prop]of [['project-title','title'],['project-summary','summary']])document.getElementById(id).addEventListener('input',e=>{snapshot();project[prop]=e.target.value;changed();});
document.getElementById('add').addEventListener('click',()=>{if(project.blocks.length>=100){status.textContent='실증 화면에서는 최대 100개까지 추가할 수 있습니다.';return;}snapshot();const b=createBlock(document.getElementById('block-type').value);project.blocks.push(b);selected=b.id;changed();renderList();renderFields();});
document.getElementById('duplicate').addEventListener('click',()=>{if(project.blocks.length>=100){status.textContent='최대 블록 개수를 초과했습니다.';return;}snapshot();const i=project.blocks.findIndex(b=>b.id===selected);project.blocks=duplicateBlock(project.blocks,selected);selected=project.blocks[i+1].id;changed();renderList();renderFields();});
document.getElementById('delete').addEventListener('click',()=>{snapshot();const i=project.blocks.findIndex(b=>b.id===selected);project.blocks=project.blocks.filter(b=>b.id!==selected);selected=project.blocks[Math.min(i,project.blocks.length-1)]?.id;changed();renderList();renderFields();});
document.getElementById('undo').addEventListener('click',()=>{if(!history.length)return;project=history.pop();if(!project.blocks.some(b=>b.id===selected))selected=project.blocks[0]?.id;changed();refresh();document.getElementById('undo').disabled=history.length===0;});
document.getElementById('save').addEventListener('click',()=>{try{validateProject(project);localStorage.setItem(key,JSON.stringify(project));dirty=false;status.textContent='이 브라우저에 저장했습니다. 새로고침해도 유지됩니다.';}catch{status.textContent='저장하지 못했습니다. 브라우저 저장 공간·설정을 확인해 주세요. 편집 내용은 화면에 유지됩니다.';}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
function sizePreview(){const width=+document.getElementById('preview-width').value;const stage=document.getElementById('preview-stage');const scale=Math.min(1,(stage.clientWidth-32)/width);preview.style.width=`${width}px`;preview.style.transform=`scale(${scale})`;stage.style.height=`${(1200*scale+32)/16}rem`;}
document.getElementById('preview-width').addEventListener('change',sizePreview);new ResizeObserver(sizePreview).observe(document.getElementById('preview-stage'));
refresh();status.textContent=loadError?'저장 데이터를 읽지 못해 테스트 프로젝트를 표시합니다. 기존 저장은 덮어쓰지 않았습니다.':'편집 후 브라우저에 저장해 주세요.';sizePreview();
